name: Deploy ke GitHub Pages

on:
  push:
    branches:
      - main  # Menjalankan workflow setiap ada perubahan di branch utama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: "."

      - name: Deploy ke GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
